### ISSUE TITLE
Error: " Import failed.  Object Reference not set to an instance of an object"

### ISSUE THREAD

**Issue by plangdon84** [djdookie/Advisor#4]
on attempting to import deck archtypes from the plugins menu, It takes a few minutes, attempts to import ~230 decks. It will continue progress through 50-75% complete.  Then it will stop and the following error is displayed. In game, no deck archtypes are identified, and the plugin is on.

![image](https://cloud.githubusercontent.com/assets/1389876/22799750/e5d3785e-eed4-11e6-967c-049f5b39b363.png)

**Comment by plangdon84** [comment]
I was able to successfully update when disconnected from my VPN.  It might have been a network performance issue.  not sure.

**Comment by djdookie** [comment]
Hi @plangdon84,
thanks for your feedback. Sounds like connection problems. I will try to figure that out.
If I am right, a better message to the user should do the job.

Additional info: The reason no archetype decks were identified is because all imported decks are saved at once, after finishing all downloads. Since the download stopped for you, no decks were saved at all. This prevents incomplete imports.

**Comment by djdookie** [comment]
Improved error handling for connection problems with 11f2e8bcf28dd327b40524db211b865059cf17a9
