### ISSUE TITLE
Update Assembly Version

### ISSUE THREAD

**Issue by ChristopherSteiner** [djdookie/Advisor#8]
Currently all releases have the assembly version 1.0.0.0. Can you update the assembly version in the assembly info when releasing a new update, so that I can determine which version I have? And probablly display the number of the currently installed version in the settings?

**Comment by djdookie** [comment]
Hi Christopher,
yeah I can do that.
I thought it's not necessary for HDT plugins since you can see the version in the plugin settings if you select it.

![grafik](https://cloud.githubusercontent.com/assets/17240204/22895105/acf1c2b2-f21b-11e6-9199-d61150e949a3.png)

Done in e54fcffa7531a105c6202d6a901d4f3fc9a4b8fc
